<?php
namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        ProductImage::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $category = Category::pluck('id');
        $brand    = Brand::pluck('id');

        $products = [
            [
                'product_uid'       => '1080992427',
                'sku'               =>'GXE3-1500IRT2UXL',
                'name'              => 'Vertiv Liebert GXE3-1500IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 1500VA/1350W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-1500IRT2UXL)',
                'long_description'  => 'Vertiv Liebert GXE UPS 1500VA/1350W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-1500IRT2UXL) - With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management| 2-Year Warranty | Includes Rack mounting kit | (8) IEC60320 C13 outlets |Fast recharge with the internal battery charger (6 Amps maximum)',
                'thumb_image'       => 'https://content.etilize.com/300/1080992427.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992442',
                'sku'               =>'GXE3-1000IRT2UXL',
                'name'              => 'VERTIV GXE3-1000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 1000VA/900W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-1000IRT2UXL)',
                'long_description'  => 'Vertiv Liebert GXE UPS 1000VA/900W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-1000IRT2UXL) - With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management| 2-Year Warranty | Includes Rack mounting kit | (8) IEC60320 C13 outlets |Fast recharge with the internal battery charger (6 Amps maximum)',
                'thumb_image'       => 'https://content.etilize.com/300/1080992442.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992459',
                'sku'               =>'GXE3-3000IRT2UXL',
                'name'              => 'VERTIV GXE3-3000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 3000VA/2700W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-3000IRT2UXL)',
                'long_description'  => 'Vertiv Liebert GXE UPS 3000VA/2700W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-3000IRT2UXL) - With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management| 2-Year Warranty | Includes Rack mounting kit | (8) IEC60320 C13 outlets |Fast recharge with the internal battery charger (6 Amps maximum)',
                'thumb_image'       => 'https://content.etilize.com/300/1080992459.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992475',
                'sku'               =>'GXE3-2000IRT2UXL',
                'name'              => 'Vertiv Liebert GXE3-2000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 2000VA/1800W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-2000IRT2UXL)',
                'long_description'  => 'Vertiv Liebert GXE UPS 2000VA/1800W 230V Online Double Conversion Rack/Tower | Lead Acid VRLA Battery | Optional battery cabinets (GXE3-2000IRT2UXL) - With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management| 2-Year Warranty | Includes Rack mounting kit | (8) IEC60320 C13 outlets |Fast recharge with the internal battery charger (6 Amps maximum)',
                'thumb_image'       => 'https://content.etilize.com/300/1080992475.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992491',
                'sku'               =>'GXE3-2000IMT',
                'name'              => 'Vertiv Liebert GXE3-2000IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 2000VA/1800W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-2000IMT)',
                'long_description'  => 'Vertiv Liebert GXE UPS 2000VA/1800W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-2000IMT) - Essential protection UPS with high performance | With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management|| 2-Year Warranty| (8) IEC60320 C13 outlets to connect easily multiple devices',
                'thumb_image'       => 'https://content.etilize.com/300/1080992491.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992505',
                'sku'               =>'GXE3-3000IMT',
                'name'              => 'Vertiv Liebert GXE3-3000IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 3000VA/2700W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF |Lead Acid VRLA Battery (GXE3-3000IMT)',
                'long_description'  => 'Vertiv Liebert GXE UPS 3000VA/2700W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF |Lead Acid VRLA Battery (GXE3-3000IMT) - Essential protection UPS with high performance | With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management|| 2-Year Warranty| (8) IEC60320 C13 outlets to connect easily multiple devices',
                'thumb_image'       => 'https://content.etilize.com/300/1080992505.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992507',
                'sku'               =>'GXE3-1500IMT',
                'name'              => 'Vertiv Liebert GXE3-1500IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 1500VA/1350W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-1500IMT)',
                'long_description'  => 'Vertiv Liebert GXE UPS 1500VA/1350W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-1500IMT) - Essential protection UPS with high performance | With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management|| 2-Year Warranty| (8) IEC60320 C13 outlets to connect easily multiple devices',
                'thumb_image'       => 'https://content.etilize.com/300/1080992507.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1080992509',
                'sku'               =>'GXE3-1000IMT',
                'name'              => 'Vertiv Liebert GXE3-1000IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXE UPS 1000VA/900W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-1000IMT)',
                'long_description'  => 'Vertiv Liebert GXE UPS 1000VA/900W 230V Online Double Conversion Tower UPS | High output power factor 0.9 PF | Lead Acid VRLA Battery (GXE3-1000IMT) - Essential protection UPS with high performance | With LCD Display | Free Vertiv Power Assist software for local UPS status and shutdown, or Vertiv Power Insight for remote network management|| 2-Year Warranty| (8) IEC60320 C13 outlets to connect easily multiple devices',
                'thumb_image'       => 'https://content.etilize.com/300/1080992509.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946040',
                'sku'               =>'PSA650-PH',
                'name'              => 'Vertiv Liebert PSA650-PH UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert PS-PH UPS 650VA/360W 230V Line Interactive AVR | Power backup for consumer electronic devices (PSA650-PH)',
                'long_description'  => 'Vertiv Liebert PS-PH UPS 650VA/360W 230V Line Interactive AVR | Power backup for consumer electronic devices (PSA650-PH) - Fuse protection, High Surge Resistant, with 3 Colors LED status light | for desktop computers, router/modem, gaming peripherals, smart home equipment | Built-in boost and buck AVR',
                'thumb_image'       => 'https://content.etilize.com/300/1081946040.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946043',
                'sku'               =>'PSA720-SOHO-LITE',
                'name'              => 'Vertiv Liebert PSA720-SOHO-LITE UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert Liebert PSA720-SOHO-LITE 720VA/360W 230VAC Line Interactive AVR |for SOHO applications (PSA720-SOHO-LITE)',
                'long_description'  => 'Vertiv Liebert Liebert PSA720-SOHO-LITE 720VA/360W 230VAC Line Interactive AVR |for SOHO applications (PSA720-SOHO-LITE) - Fuse protection, High Surge Resistant, with 3 Colors LED status light | for desktop computers, router/modem, gaming peripherals, Point of sales system/cah or payment machine | Built-in boost and buck AVR',
                'thumb_image'       => 'https://content.etilize.com/300/1081946043.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946045',
                'sku'               =>'PSA650-SOHO',
                'name'              => 'Vertiv Liebert PSA650-SOHO UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert PSA5 itON-SOHO UPS 650VA/390W 162-290VAC Line Interactive UPS',
                'long_description'  => 'Vertiv Liebert PSA5 itON-SOHO UPS 650VA/390W 162-290VAC Line Interactive UPS - Compact size and lightweight | Built-in Boost and Buck AVR | Surge protection against transient voltages | Universal sockets',
                'thumb_image'       => 'https://content.etilize.com/300/1081946045.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946047',
                'sku'               =>'EDGE-1000IRM1U',
                'name'              => 'VERTIV EDGE-1000IRM1U UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 1000VA 900W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase|0.9 PF(EDGE-1000IRM1U)',
                'long_description'  => 'Vertiv Edge UPS - 1000VA 900W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase|0.9 PF(EDGE-1000IRM1U) - Compact 1U Rack | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946047.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946049',
                'sku'               =>'EDGE-3000IRT3UXL',
                'name'              => 'VERTIV EDGE-3000IRT3UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS 3000VA 2700W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-3000IRT3UXL)',
                'long_description'  => 'Vertiv Edge UPS 3000VA 2700W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-3000IRT3UXL) - Rotatable LCD Monitor | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty |Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946049.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946054',
                'sku'               =>'GXT5-750IRT2UXL',
                'name'              => 'Vertiv Liebert GXT5-750IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT5 750VA/750W 230VAC Online Double Conversion UPS',
                'long_description'  => 'Vertiv Liebert GXT5 750VA/750W 230VAC Online Double Conversion UPS - Double Conversion |2U | Color/Graphic LCD| 3-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946054.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946055',
                'sku'               =>'EDGE-1500IRM1U',
                'name'              => 'VERTIV EDGE-1500IRM1U UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 1500VA 1350W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase|0.9 PF (EDGE-1500IRM1U)',
                'long_description'  => 'Vertiv Edge UPS - 1500VA 1350W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase|0.9 PF (EDGE-1500IRM1U) - Compact 1U Rack | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946055.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946061',
                'sku'               =>'EDGE-1500IMT',
                'name'              => 'VERTIV EDGE-1500IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 1500VA 1350W 230V Line Interactive AVR Mini Tower Battery Backup Single Phase |0.9 PF (EDGE-1500IMT)',
                'long_description'  => 'Vertiv Edge UPS - 1500VA 1350W 230V Line Interactive AVR Mini Tower Battery Backup Single Phase |0.9 PF (EDGE-1500IMT) - Plug and Play | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946061.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946062',
                'sku'               =>'PSA1000-SOHO',
                'name'              => 'Vertiv Liebert PSA1000-SOHO UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert PSA5 itON-SOHO UPS 1000VA/600W 162-290VAC Line Interactive UPS',
                'long_description'  => 'Vertiv Liebert PSA5 itON-SOHO UPS 1000VA/600W 162-290VAC Line Interactive UPS - Compact size and lightweight | Built-in Boost and Buck AVR | Surge protection against transient voltages | Universal sockets',
                'thumb_image'       => 'https://content.etilize.com/300/1081946062.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946063',
                'sku'               =>'EDGE-1500IRT2UXL',
                'name'              => 'VERTIV EDGE-1500IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS 1500VA 1350W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase|0.9 PF (EDGE-1500IRT2UXL)',
                'long_description'  => 'Vertiv Edge UPS 1500VA 1350W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase|0.9 PF (EDGE-1500IRT2UXL) - Rotatable LCD Monitor | 0.9 PF | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946063.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946064',
                'sku'               =>'EDGE-1000IMT',
                'name'              => 'VERTIV EDGE-1000IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 1000VA 900W 230V Line Interactive AVR Mini Tower Battery Backup Single Phase |0.9 PF (EDGE-1000IMT)',
                'long_description'  => 'Vertiv Edge UPS - 1000VA 900W 230V Line Interactive AVR Mini Tower Battery Backup Single Phase |0.9 PF (EDGE-1000IMT) - Plug and Play | Sine Wave Output on Battery | 2 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946064.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946065',
                'sku'               =>'EDGE-500IRM1U',
                'name'              => 'VERTIV EDGE-500IRM1U UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 500VA 450W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-500IRM1U)',
                'long_description'  => 'Vertiv Edge UPS - 500VA 450W 230V 1U Line Interactive AVR Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-500IRM1U) - Compact 1U Rack | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty | Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946065.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946072',
                'sku'               =>'GXT5-1500IRT2UXL',
                'name'              => 'Vertiv Liebert GXT5-1500IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT5 UPS - 1500VA/1500W 230V | Online Rack Tower Energy Star',
                'long_description'  => 'Vertiv Liebert GXT5 UPS - 1500VA/1500W 230V | Online Rack Tower Energy Star - Double Conversion | 2U | Optional RDU101 Card| Color/Graphic LCD| 3-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946072.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946075',
                'sku'               =>'PSA850-SOHO',
                'name'              => 'Vertiv Liebert PSA850-SOHO UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert PSA5 itON-SOHO UPS 850VA/510W 162-290VAC Line Interactive UPS',
                'long_description'  => 'Vertiv Liebert PSA5 itON-SOHO UPS 850VA/510W 162-290VAC Line Interactive UPS - Compact size and lightweight | Built-in Boost and Buck AVR | Surge protection against transient voltages | Universal sockets',
                'thumb_image'       => 'https://content.etilize.com/300/1081946075.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946078',
                'sku'               =>'GXT-1000MTPLUSC230',
                'name'              => 'Vertiv Liebert GXT-1000MTPLUSC230 UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT MT+ 1kVA/900W 230V Online Standard-Run Transformer-free UPS',
                'long_description'  => 'Vertiv Liebert GXT MT+ 1kVA/900W 230V Online Standard-Run Transformer-free UPS - 0.9 Output Power Factor | Graphic LCD| Tower | 2-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946078.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946079',
                'sku'               =>'EDGE-3000IRT2UXL',
                'name'              => 'VERTIV EDGE-3000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS 3000VA 2700W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-3000IRT2UXL)',
                'long_description'  => 'Vertiv Edge UPS 3000VA 2700W 230V 2U Line Interactive AVR Tower/Rack Mount Battery Backup Single Phase |0.9 PF (EDGE-3000IRT2UXL) - Rotatable LCD Monitor | Sine Wave Output on Battery | 3 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty |Network Edge',
                'thumb_image'       => 'https://content.etilize.com/300/1081946079.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946083',
                'sku'               =>'GXT5-3000IRT2UXL',
                'name'              => 'Vertiv Liebert GXT5-3000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT5 UPS - 3000VA/3000W 230V | Online Rack Tower Energy Star',
                'long_description'  => 'Vertiv Liebert GXT5 UPS - 3000VA/3000W 230V | Online Rack Tower Energy Star - Double Conversion | 2U | Optional RDU101 Card| Color/Graphic LCD| 3-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946083.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946084',
                'sku'               =>'GXT5-2000IRT2UXL',
                'name'              => 'Vertiv Liebert GXT5-2000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT5 UPS - 2000VA/2000W 230V | Online Rack Tower Energy Star',
                'long_description'  => 'Vertiv Liebert GXT5 UPS - 2000VA/2000W 230V | Online Rack Tower Energy Star - Double Conversion | 2U | Optional RDU101 Card| Color/Graphic LCD| 3-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946084.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946085',
                'sku'               =>'GXT-2000MTPLUSC230',
                'name'              => 'Vertiv Liebert GXT-2000MTPLUSC230 UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT MT+ 2kVA/1800W 230V Online Standard-Run Transformer-free UPS',
                'long_description'  => 'Vertiv Liebert GXT MT+ 2kVA/1800W 230V Online Standard-Run Transformer-free UPS - 0.9 Output Power Factor | Graphic LCD| Tower | 2-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946085.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946087',
                'sku'               =>'GXT-3000MTPLUSC230',
                'name'              => 'Vertiv Liebert GXT-3000MTPLUSC230 UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT MT+ 3kVA/2700W 230V Online Standard-Run Transformer-free UPS',
                'long_description'  => 'Vertiv Liebert GXT MT+ 3kVA/2700W 230V Online Standard-Run Transformer-free UPS - 0.9 Output Power Factor | Graphic LCD| Tower | 2-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946087.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1081946088',
                'sku'               =>'GXT5-1000IRT2UXL',
                'name'              => 'Vertiv Liebert GXT5-1000IRT2UXL UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Liebert GXT5 1000VA/1000W 230VAC Online Double Conversion UPS',
                'long_description'  => 'Vertiv Liebert GXT5 1000VA/1000W 230VAC Online Double Conversion UPS - Double Conversion |2U | Color/Graphic LCD| 3-Year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1081946088.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1082310576',
                'sku'               =>'EDGE-750IMT',
                'name'              => 'VERTIV EDGE-750IMT UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv Edge UPS - 750VA 675W 230V Line Interactive AVR Mini Tower |0.9 PF (EDGE-750IMT)',
                'long_description'  => 'Vertiv Edge UPS - 750VA 675W 230V Line Interactive AVR Mini Tower |0.9 PF (EDGE-750IMT) - Plug and Play | Sine Wave Output on Battery | 2 Programmable Outlets | Vertiv Intellislot SNMP/Webcards available for remote power management | 3-year Warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1082310576.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1086228068',
                'sku'               =>'PSA6E-2200IT-IEC',
                'name'              => 'VERTIV PSA6E-2200IT-IEC UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv PowerUPS 200 Essential PSA6E-2200IT-IEC, 2200VA/1225W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty',
                'long_description'  => 'Vertiv PowerUPS 200 Essential PSA6E-2200IT-IEC, 2200VA/1225W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty - uninterruptible power supply, small UPS, POS UPS, 230VAC, line-interactive, basic power protection, automatic voltage regulation, AVR, Vertiv Power Assist, user-replaceable batteries, LED indicators, dataline surge protection, alarm mute, PWM simulated sine wave, IEC, affordable, eco-friendly, warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1086228068.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1086228101',
                'sku'               =>'PSA6E-1600IT-IEC',
                'name'              => 'VERTIV PSA6E-1600IT-IEC UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv PowerUPS 200 Essential PSA6E-1600IT-IEC, 1600VA/925W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty',
                'long_description'  => 'Vertiv PowerUPS 200 Essential PSA6E-1600IT-IEC, 1600VA/925W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty - uninterruptible power supply, small UPS, POS UPS, 230VAC, line-interactive, basic power protection, automatic voltage regulation, AVR, Vertiv Power Assist, user-replaceable batteries, LED indicators, dataline surge protection, alarm mute, PWM simulated sine wave, IEC, affordable, eco-friendly, warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1086228101.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1086228134',
                'sku'               =>'PSA6E-600IT-IEC',
                'name'              => 'VERTIV PSA6E-600IT-IEC UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv PowerUPS 200 Essential PSA6E-600IT-IEC, 600VA/315W, AVR, User-Replaceable Batteries, Battery Backup, 4 IEC Outlets, Two-Year Warranty',
                'long_description'  => 'Vertiv PowerUPS 200 Essential PSA6E-600IT-IEC, 600VA/315W, AVR, User-Replaceable Batteries, Battery Backup, 4 IEC Outlets, Two-Year Warranty - uninterruptible power supply, small UPS, POS UPS, 230VAC, line-interactive, basic power protection, automatic voltage regulation, AVR, Vertiv Power Assist, user-replaceable batteries, LED indicators, alarm mute, PWM simulated sine wave, IEC, affordable, eco-friendly, warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1086228134.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],
            [
                'product_uid'       => '1086228141',
                'sku'               =>'PSA6E-1000IT-IEC',
                'name'              => 'VERTIV PSA6E-1000IT-IEC UPS',
                'slug'              => 'slug',
                'category_id'       => 2,
                'brand_id'          => 1,
                'price'             => 0,
                'offer_price'       => 0,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Vertiv PowerUPS 200 Essential PSA6E-1000IT-IEC, 1000VA/525W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty',
                'long_description'  => 'Vertiv PowerUPS 200 Essential PSA6E-1000IT-IEC, 1000VA/525W, AVR, User-Replaceable Batteries, Battery Backup, 6 IEC Outlets, Two-Year Warranty - uninterruptible power supply, small UPS, POS UPS, 230VAC, line-interactive, basic power protection, automatic voltage regulation, AVR, Vertiv Power Assist, user-replaceable batteries, LED indicators, dataline surge protection, alarm mute, PWM simulated sine wave, IEC, affordable, eco-friendly, warranty',
                'thumb_image'       => 'https://content.etilize.com/300/1086228141.jpg?_672b0e9d290907d2bde6cd5e921314d9e4a14920',
            ],

        ];

        $inc    = 1;

        foreach ($products as $prod) {
            $prod['slug'] = Str::slug($prod['name']);
            Product::create($prod);
        }

    }
}
