<?php
namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use Illuminate\Database\Seeder;

class ProductSeederCopy extends Seeder
{
    public function run(): void
    {
        \DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Product::truncate();
        ProductImage::truncate();
        \DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $images = [
'assets/img/project/project_inner_3.jpg', 'assets/img/project/project_1_1.jpg', 'assets/img/project/project_1_2.jpg', 'assets/img/project/project_1_3.jpg', 'assets/img/project/project_1_4.jpg', 'assets/img/project/project_2_1.jpg', 'assets/img/project/project_2_2.jpg', 'assets/img/project/project_2_3.jpg', 'assets/img/project/project_2_4.jpg', 'assets/img/project/project_3_1.jpg', 'assets/img/project/project_3_2.jpg', 'assets/img/project/project_3_3.jpg', 'assets/img/project/project_3_4.jpg', 'assets/img/project/project_3_5.jpg', 'assets/img/project/project_3_6.jpg', 'assets/img/project/project_3_7.jpg', 'assets/img/project/project_3_8.jpg', 'assets/img/project/project_3_9.jpg', 'assets/img/project/project_4_1.jpg', 'assets/img/project/project_4_2.jpg', 'assets/img/project/project_4_3.jpg', 'assets/img/project/project_4_4.jpg', 'assets/img/project/project_4_5.jpg', 'assets/img/project/project_4_6.jpg', 'assets/img/project/project_5_1.jpg', 'assets/img/project/project_5_2.jpg', 'assets/img/project/project_5_3.jpg', 'assets/img/project/project_5_4.jpg', 'assets/img/project/project_5_5.jpg', 'assets/img/project/project_5_6.jpg', 'assets/img/project/project_5_7.jpg', 'assets/img/project/project_5_8.jpg', 'assets/img/project/project_5_9.jpg', 'assets/img/project/project_details.jpg', 'assets/img/project/project_inner_1.jpg', 'assets/img/project/project_inner_2.jpg', 'assets/img/service/service_1_1.jpg', 'assets/img/service/service_1_2.jpg', 'assets/img/service/service_1_3.jpg', 'assets/img/service/service_1_4.jpg', 'assets/img/service/service_1_5.jpg', 'assets/img/service/service_1_6.jpg', 'assets/img/service/service_1_7.jpg', 'assets/img/service/service_1_8.jpg', 'assets/img/service/service_2_1.jpg', 'assets/img/service/service_2_2.jpg', 'assets/img/service/service_2_3.jpg', 'assets/img/service/service_2_4.jpg', 'assets/img/service/service_2_5.jpg', 'assets/img/service/service_2_6.jpg', 'assets/img/service/service_details.jpg', 'assets/img/service/service_inner_1.jpg', 'assets/img/service/service_inner_2.jpg', 'assets/img/service/service_overlay.jpg', 'assets/img/service/service_overlay_1.jpg', 'assets/img/service/service_overlay_2.jpg', 'assets/img/service/service_overlay_3.jpg', 'assets/img/service/service_overlay_4.jpg'];


        $category = Category::pluck('id');
        $brand    = Brand::pluck('id');

        $products = [
            [
                'name'              => 'Cisco Router 1000',
                'slug'              => 'cisco-router-1000',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 50000,
                'offer_price'       => 45000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High performance router for enterprise.',
                'long_description'  => 'The Cisco Router 1000 is designed for high-performance networking in enterprise environments. With advanced features and robust security, it ensures reliable connectivity and data protection.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'APC Smart UPS 1500',
                'slug'              => 'apc-smart-ups-1500',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 120000,
                'offer_price'       => 110000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Reliable UPS backup for servers.',
                'long_description'  => 'The APC Smart UPS 1500 provides reliable backup power for servers and critical equipment. It features advanced battery management and energy-efficient operation to ensure optimal performance during power outages.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Hikvision IP Camera DS-2CD2143G0-I',
                'slug'              => 'hikvision-ip-camera-ds-2cd2143g0-i',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 8000,
                'offer_price'       => 7500,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => '4MP outdoor IP camera with night vision.',
                'long_description'  => 'The Hikvision IP Camera DS-2CD2143G0-I is a high-resolution outdoor camera that offers 4MP video quality and night vision capabilities. It is ideal for surveillance in various environments, providing clear images even in low light conditions.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'HP ProLiant DL380 Gen10 Server',
                'slug'              => 'hp-proliant-dl380-gen10-server',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 250000,
                'offer_price'       => 240000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Versatile and powerful server for data centers.',
                'long_description'  => 'The HP ProLiant DL380 Gen10 Server is a versatile and powerful server designed for data centers and enterprise applications. It features advanced security, scalability, and performance to meet the demands of modern IT environments.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Vertiv Liebert GXT4 UPS 3000VA',
                'slug'              => 'vertiv-liebert-gxt4-ups-3000va',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 200000,
                'offer_price'       => 190000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-capacity UPS for critical systems.',
                'long_description'  => 'The Vertiv Liebert GXT4 UPS 3000VA is a high-capacity uninterruptible power supply designed to protect critical systems from power disturbances. It offers advanced features such as online double conversion technology and scalable runtime options.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Dell PowerEdge R740 Server',
                'slug'              => 'dell-poweredge-r740-server',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 230000,
                'offer_price'       => 220000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-performance server for virtualization.',
                'long_description'  => 'The Dell PowerEdge R740 Server is designed for high-performance computing and virtualization workloads. It features a flexible architecture, advanced management capabilities, and robust security features to support modern data center needs.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Lenovo ThinkSystem SR650 Server',
                'slug'              => 'lenovo-thinksystem-sr650-server',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 210000,
                'offer_price'       => 200000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Reliable server for enterprise applications.',
                'long_description'  => 'The Lenovo ThinkSystem SR650 Server is a reliable and scalable server designed for enterprise applications. It offers high performance, advanced security features, and flexible storage options to meet the demands of modern IT environments.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Netgear Nighthawk Pro Gaming XR500 Router',
                'slug'              => 'netgear-nighthawk-pro-gaming-xr500-router',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 30000,
                'offer_price'       => 28000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-performance gaming router.',
                'long_description'  => 'The Netgear Nighthawk Pro Gaming XR500 Router is designed for gamers who demand high performance and low latency. It features advanced QoS, geo-filtering, and customizable settings to optimize gaming experiences.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Ubiquiti UniFi Switch 24 PoE',
                'slug'              => 'ubiquiti-unifi-switch-24-poe',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 60000,
                'offer_price'       => 55000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Managed PoE switch for network expansion.',
                'long_description'  => 'The Ubiquiti UniFi Switch 24 PoE is a managed Power over Ethernet switch that provides network expansion with PoE capabilities. It features a sleek design, advanced management options, and seamless integration with the UniFi ecosystem.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920
+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-2',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-3',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-4',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Cisco Router 10001',
                'slug'              => 'cisco-router-10001',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 50000,
                'offer_price'       => 45000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High performance router for enterprise.',
                'long_description'  => 'The Cisco Router 1000 is designed for high-performance networking in enterprise environments. With advanced features and robust security, it ensures reliable connectivity and data protection.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'APC Smart UPS 15001',
                'slug'              => 'apc-smart-ups-15001',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 120000,
                'offer_price'       => 110000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Reliable UPS backup for servers.',
                'long_description'  => 'The APC Smart UPS 1500 provides reliable backup power for servers and critical equipment. It features advanced battery management and energy-efficient operation to ensure optimal performance during power outages.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Hikvision IP Camera DS-2CD2143G0-I1',
                'slug'              => 'hikvision-ip-camera-ds-2cd2143g0-i1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 8000,
                'offer_price'       => 7500,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => '4MP outdoor IP camera with night vision.',
                'long_description'  => 'The Hikvision IP Camera DS-2CD2143G0-I is a high-resolution outdoor camera that offers 4MP video quality and night vision capabilities. It is ideal for surveillance in various environments, providing clear images even in low light conditions.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'HP ProLiant DL380 Gen10 Server1',
                'slug'              => 'hp-proliant-dl380-gen10-server1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 250000,
                'offer_price'       => 240000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Versatile and powerful server for data centers.',
                'long_description'  => 'The HP ProLiant DL380 Gen10 Server is a versatile and powerful server designed for data centers and enterprise applications. It features advanced security, scalability, and performance to meet the demands of modern IT environments.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Vertiv Liebert GXT4 UPS 3000VA1',
                'slug'              => 'vertiv-liebert-gxt4-ups-3000va1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 200000,
                'offer_price'       => 190000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-capacity UPS for critical systems.',
                'long_description'  => 'The Vertiv Liebert GXT4 UPS 3000VA is a high-capacity uninterruptible power supply designed to protect critical systems from power disturbances. It offers advanced features such as online double conversion technology and scalable runtime options.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Dell PowerEdge R740 Server1',
                'slug'              => 'dell-poweredge-r740-server1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 230000,
                'offer_price'       => 220000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-performance server for virtualization.',
                'long_description'  => 'The Dell PowerEdge R740 Server is designed for high-performance computing and virtualization workloads. It features a flexible architecture, advanced management capabilities, and robust security features to support modern data center needs.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Lenovo ThinkSystem SR650 Server1',
                'slug'              => 'lenovo-thinksystem-sr650-server1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 210000,
                'offer_price'       => 200000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Reliable server for enterprise applications.',
                'long_description'  => 'The Lenovo ThinkSystem SR650 Server is a reliable and scalable server designed for enterprise applications. It offers high performance, advanced security features, and flexible storage options to meet the demands of modern IT environments.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Netgear Nighthawk Pro Gaming XR500 Router1',
                'slug'              => 'netgear-nighthawk-pro-gaming-xr500-router1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 30000,
                'offer_price'       => 28000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'High-performance gaming router.',
                'long_description'  => 'The Netgear Nighthawk Pro Gaming XR500 Router is designed for gamers who demand high performance and low latency. It features advanced QoS, geo-filtering, and customizable settings to optimize gaming experiences.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Ubiquiti UniFi Switch 24 PoE1',
                'slug'              => 'ubiquiti-unifi-switch-24-poe1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 60000,
                'offer_price'       => 55000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Managed PoE switch for network expansion.',
                'long_description'  => 'The Ubiquiti UniFi Switch 24 PoE is a managed Power over Ethernet switch that provides network expansion with PoE capabilities. It features a sleek design, advanced management options, and seamless integration with the UniFi ecosystem.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS1',
                'slug'              => 'synology-diskstation-ds920-plus-nas1',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920
+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS1',
                'slug'              => 'synology-diskstation-ds920-plus-nas-11',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS1',
                'slug'              => 'synology-diskstation-ds920-plus-nas-21',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-31',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],
            [
                'name'              => 'Synology DiskStation DS920+ NAS',
                'slug'              => 'synology-diskstation-ds920-plus-nas-41',
                'category_id'       => $category->random(),
                'brand_id'          => $brand->random(),
                'price'             => 80000,
                'offer_price'       => 75000,
                'product_type'      => 'simple',
                'status'            => 1,
                'short_description' => 'Compact NAS for home and small office.',
                'long_description'  => 'The Synology DiskStation DS920+ NAS is a compact and powerful network-attached storage solution designed for home and small office use. It features advanced data management, file sharing, and backup capabilities to keep your data secure and accessible.',
                'thumb_image'       => $images[array_rand($images)],
            ],

        ];

        $inc    = 1;
        foreach ($products as $prod) {
            $product_images[] = [
                'product_id' => $inc,
                'image'      => $images[array_rand($images)],
                'is_main'    => 1,
            ];
            $product_images[] = [
                'product_id' => $inc,
                'image'      => $images[array_rand($images)],
                'is_main'    => 0,
            ];
            $product_images[] = [
                'product_id' => $inc,
                'image'      => $images[array_rand($images)],
                'is_main'    => 0,
            ];
            $inc++;
        }

        foreach ($products as $prod) {
            Product::create($prod);
        }

        foreach ($product_images as $image) {
            // echo "---".$image['product_id']."---";
            Product::find($image['product_id'])->images()->create($image);
            // print_r($image);
        }
    }
}
